#ifndef SPACEGUY_BANKS_SHARED_H
#define SPACEGUY_BANKS_SHARED_H

// Texture bank
#define SG_MAX_TEXTURES 20

// Uniform bank
#define SG_UNIFORM_FLOAT_COUNT 100
#define SG_UNIFORM_VEC2_COUNT 100
#define SG_UNIFORM_VEC3_COUNT 100
#define SG_UNIFORM_VEC4_COUNT 100
#define SG_UNIFORM_MAT4_COUNT 100

#define SG_UNIFORM_FLOAT_SLOTS ((SG_UNIFORM_FLOAT_COUNT + 3) / 4)
#define SG_UNIFORM_VEC2_SLOTS ((SG_UNIFORM_VEC2_COUNT + 1) / 2)
#define SG_UNIFORM_VEC3_SLOTS (SG_UNIFORM_VEC3_COUNT)
#define SG_UNIFORM_VEC4_SLOTS (SG_UNIFORM_VEC4_COUNT)
#define SG_UNIFORM_MAT4_SLOTS (SG_UNIFORM_MAT4_COUNT * 4)

#define SG_UNIFORM_FLOAT_FROM 0
#define SG_UNIFORM_VEC2_FROM (SG_UNIFORM_FLOAT_FROM + SG_UNIFORM_FLOAT_SLOTS)
#define SG_UNIFORM_VEC3_FROM (SG_UNIFORM_VEC2_FROM + SG_UNIFORM_VEC2_SLOTS)
#define SG_UNIFORM_VEC4_FROM (SG_UNIFORM_VEC3_FROM + SG_UNIFORM_VEC3_SLOTS)
#define SG_UNIFORM_MAT4_FROM (SG_UNIFORM_VEC4_FROM + SG_UNIFORM_VEC4_SLOTS)

#define SG_UNIFORM_TOTAL_SLOTS (SG_UNIFORM_MAT4_FROM + SG_UNIFORM_MAT4_SLOTS)

// Scene stuff
// Vec4
#define SG_SUN_INTENSITY_INDEX (SG_UNIFORM_VEC4_COUNT - 3)
#define SG_SUN_DIR_INDEX (SG_UNIFORM_VEC4_COUNT - 2)
#define SG_VIEW_POS_INDEX (SG_UNIFORM_VEC4_COUNT - 1)
// Mat4
#define SG_PROJ_INDEX (SG_UNIFORM_MAT4_COUNT - 2)
#define SG_VIEW_INDEX (SG_UNIFORM_MAT4_COUNT - 1)

// Push-constant bank
#define SG_PUSH_FLOAT_COUNT 4
#define SG_PUSH_VEC2_COUNT 4
#define SG_PUSH_VEC3_COUNT 1
#define SG_PUSH_INT_COUNT 16

#define SG_PUSH_FLOAT_SLOTS ((SG_PUSH_FLOAT_COUNT + 3) / 4)
#define SG_PUSH_VEC2_SLOTS ((SG_PUSH_VEC2_COUNT + 1) / 2)
#define SG_PUSH_VEC3_SLOTS (SG_PUSH_VEC3_COUNT)
#define SG_PUSH_INT_SLOTS ((SG_PUSH_INT_COUNT + 3) / 4)

#define SG_PUSH_FLOAT_FROM 0
#define SG_PUSH_VEC2_FROM (SG_PUSH_FLOAT_FROM + SG_PUSH_FLOAT_SLOTS)
#define SG_PUSH_VEC3_FROM (SG_PUSH_VEC2_FROM + SG_PUSH_VEC2_SLOTS)
#define SG_PUSH_INT_FROM (SG_PUSH_VEC3_FROM + SG_PUSH_VEC3_SLOTS)

#define SG_PUSH_TOTAL_SLOTS (SG_PUSH_INT_FROM + SG_PUSH_INT_SLOTS)
#define SG_PUSH_TOTAL_BYTES (SG_PUSH_TOTAL_SLOTS * 16)

#define SG_PUSH_MODEL_INDEX 0

#endif
